export { default as ProtectedRoute } from './ProtectedRoute';
export { default as Header } from './Header/Header';
export { default as Login } from './Login/Login';
export { default as Sidebar } from './Sidebar/Sidebar';
export { default as Home } from './Home/Home';
export { default as CheckIn } from './CheckIn/CheckIn';
export { default as Journals } from './Journals/Journals';
export { default as ViewJournal } from './ViewJournal/ViewJournal';
export { default as ErrorPopUp } from './ErrorPopUp/ErrorPopUp'; 